### ISSUE TITLE
Agreement for on-premise software

### ISSUE THREAD

**Issue by fmassot** [CommonPaper/CSA#6]
First thank you for sharing your templates here and founding this company :)

I'm building and selling an OSS on-premise software that is run by our clients on their own infrastructure and I think the CSA agreement does not fit well for that. Do you have plan to release an agreement that would be a better fit for on-premise solutions?

**Comment by bengarvey** [comment]
@fmassot Thanks. We're aware of this need and will likely have something to address it in the future. Thanks for your suggstion.
